### ISSUE TITLE
GetAmznLx.sh is missing from the repo

### ISSUE THREAD

**Issue by mikerj1** [plus3it/AMIgen7#37]
Hi, just found this repo and giving it a try.  I was prompted to run GetAmznLx.sh, but it wasn't present.  I pulled this from your AMIgen6 repo and seemed to work fine though.  Thanks

**Comment by ferricoxide** [comment]
Cool. Thanks for the bug report. I guess it got overlooked because, at this point, AMIgen7 is mostly being driven by another tool ([spel](/plus3it/spel)).

At any rate, I'll try to get that merged in before week's end.
